### PR TITLE
AKS: Remove k8s config

### LINKED ISSUE #187: Do not collect c:/k/config in AKS Windows nodes
c:/k/config contains credentials and it may not be helpful for troubleshooting. I do not have the background why we need to collect this file. @axelgMS, could you explain a bit more? Thanks.
https://github.com/Azure/azure-diskinspect-service/commit/fa3b6b626c2c7f1798d7e9cd595fbcde097f6e6b#diff-5479476b67bee0ed06b0852d806f953c23d87c96d34c7a38a1443dc53c854998

### PR DESCRIPTION
**Pull request by AbelHu**
Fix #187

### CODE REVIEW

**Comment by AbelHu** [comment]
@chintanrp Could you help to check why the Travis CI build failed?

**Review by mainred — APPROVED** [review]

**Comment by mainred** [comment]
I think you may change to not use forked repo for this PR, this is causing CI to fail. @AbelHu

**Comment by AbelHu** [comment]
@mainred I used a forked branch as I did before.

**Comment by chintanrp** [comment]
@AbelHu  - You need to create PR from branch out of master not from the forked repo.
https://github.com/Azure/azure-diskinspect-service#how-to-contribute

**Comment by AbelHu** [comment]
@chintanrp https://github.com/Azure/azure-diskinspect-service/tree/abelch/remove-k8s-config is a branch but not a forked repo

**Comment by chintanrp** [comment]
@AbelHu  -  Are you part of the group as in the instruction I provided above?

**Comment by AbelHu** [comment]
@chintanrp  I am a member of the group and I created multiple PRs before successfully, for example, https://github.com/Azure/azure-diskinspect-service/pull/186.

**Comment by AbelHu** [comment]
@chintanrp It seems like that a force push after changing the commit id works.

**Comment by AbelHu** [comment]
> @chintanrp I am a member of the group and I created multiple PRs before successfully, for example, #186.

It passed in build but still failed in deploy. Need your help, @chintanrp

**Review by chintanrp — APPROVED** [review]
LGTM

**Pull request merged**
