### PR TITLE
adding cluster-provisioning log

### PR DESCRIPTION
**Pull request by chmill**
required log to investigate AKS CSE failure

### CODE REVIEW

**Comment by CraigWiand** [comment]
Hey Chase, how big do you expect this log to be?  Is it used in scenarios other than AKS+CSE?

Can you run the [parse manifest tool](https://github.com/Azure/azure-diskinspect-service/blob/master/docs/tools.md) and add the updated markdown docs to the PR?

Thanks!

**Comment by chmill** [comment]
file size has been less than 100kb from what I've seen. ACS-Engine would also have this log as well.

**Comment by lalo** [comment]
What is the status here? This would've been (possibly) helpful for current investigations regarding CSE.

**Comment by chintanrp** [comment]
This changes has been added as a part of another manifests - #79 & #95

**Pull request closed without merging**
