### PR TITLE
adding the pod logs symlink location for ugly reading

### PR DESCRIPTION
**Pull request by chmill-zz**

### CODE REVIEW

**Comment by chmill-zz** [comment]
at a maximum right now this would be 110 text files because that's our max pod per node limit. There are some extreme pod counts per cluster but these are outliers and related to completed jobs run. So the logging of those extremes should be minimal.  A large majority would fall below the 110 count based on previous experience investigating clusters.

**Comment by chintanrp** [comment]
And what about the total size?

**Comment by chmill-zz** [comment]
file size maxed at 50mb before rolling a new log. 

The new log would be under a xxxx-json.log.1 - so we shouldn't pick this up with the given *-json.log grab.

**Comment by chintanrp** [comment]
ok, that it would be fine.

**Pull request merged**
