### PR TITLE
Add EG IID files for Linux Provisioning

### PR DESCRIPTION
**Pull request by johnsonshi**
Add files that aid in diagnosing Linux provisioning failures.

New files added:

Cloud-init configs:
`/var/cloud/cloud.cfg`
`/var/cloud/cloud.cfg.d/*.cfg`

Cloud-init runtime status:
`/run/cloud-init/cloud.cfg` (runtime-generated cfg of eligible DataSources)
`/run/cloud-init/ds-identify.log` (runtime results of identifying DataSources)
`/run/cloud-init/result.json` (DataSource search results)
`/run/cloud-init/status.json` (summary of results of different cloud-init stages)

Waagent runtime status:
`/var/lib/waagent/waagent_status.json`

Dhcp leases:
`/run/systemd/netif/leases/*`
`/var/lib/dhcp/*.leases`
`/var/lib/dhcp/*.lease`
`/var/lib/dhclient/*.leases`
`/var/lib/dhclient/*.lease`
`/var/lib/NetworkManager/*.leases`
`/var/lib/NetworkManager/*.lease`
`/run/cloud-init/dhclient.hooks/*.json`
`/var/lib/wicked/lease*`

Networking files configs (Ubuntu/Debian):
`/etc/netplan/*.yaml` (previously only gathered `50-cloud-init.yaml`)
`/etc/dhcp/*.conf` (newly-added, includes `dhclient.conf` and `dhclient-<device>.conf`)

NetworkManager configs (RHEL/CentOS):
`/var/lib/NetworkManager/*.conf`
`/var/lib/NetworkManager/conf.d/*.conf`
`/var/lib/NetworkManager/*.state` (describes the state of NetworkManager)
`/usr/lib/NetworkManager/*.conf`
`/usr/lib/NetworkManager/conf.d/*.conf`
`/run/NetworkManager/*.conf`
`/run/NetworkManager/conf.d/*.conf`
`/etc/NetworkManager/*.conf`
`/etc/NetworkManager/conf.d/*.conf`

Sysconfig Network configs (legacy networking):
`/etc/sysconfig/network/config`
`/etc/sysconfig/network/dhcp`
`/etc/sysconfig/network/ifcfg-*` (previously only gathered `/etc/sysconfig/network/ifcfg-eth*`)
`/etc/sysconfig/network-scripts/ifcfg-*` (previously only gathered `/etc/sysconfig/network-scripts/ifcfg-eth*`)
`/etc/sysconfig/network-scripts/route-*` (previously only gathered `/etc/sysconfig/network-scripts/route-eth*`)

Wicked network manager configs (SUSE/SLES):
`/etc/wicked/*.xml` (Wicked configs)

resolvconf configs:
`/run/systemd/resolve/*.conf (previously only gathered `/run/systemd/resolve/stub-resolv.conf`)
`/run/resolvconf/*.conf` (previously only gathered `/run/resolvconf/resolv.conf`)

Package manager logs (RHEL/CentOS 8+ now uses DNF by default instead of YUM):
`copy,/var/log/dnf*`

### CODE REVIEW

**Comment by CraigWiand** [comment]
_info from Johnson in offline thread_
> These files will aid in diagnosing the root cause when provisioning fails, especially for networking issues.

> The effect on EG performance will be very minimal as all of these files are very small.
Also, only about 1/4 to 1/5 of these newly-added files are present in any system (diff distros have diff locations for these files). 

@johnsonshi the CI is failing because the manifest docs are out of sync with the manifest.  Sadly it is not fully automated at check-in.  Can you take a look at the below, run the script and add the revised docs to the PR?
https://github.com/Azure/azure-diskinspect-service/blob/master/docs/tests.md#manifest-documentation-test

**Comment by johnsonshi** [comment]
> _info from Johnson in offline thread_
> 
> > These files will aid in diagnosing the root cause when provisioning fails, especially for networking issues.
> 
> > The effect on EG performance will be very minimal as all of these files are very small.
> > Also, only about 1/4 to 1/5 of these newly-added files are present in any system (diff distros have diff locations for these files).
> 
> @johnsonshi the CI is failing because the manifest docs are out of sync with the manifest. Sadly it is not fully automated at check-in. Can you take a look at the below, run the script and add the revised docs to the PR?
> https://github.com/Azure/azure-diskinspect-service/blob/master/docs/tests.md#manifest-documentation-test

Updated the docs.

**Comment by chintanrp** [comment]
@johnsonshi  - as we are adding those files in diagnostic manifest, do we know the size of those files? Because concern here is, it will increase the log collection time for that manifest which is already a biggest on so far and highly used one also.
If this is something specific scenario then let's create new manifest.

**Comment by jasonzio** [comment]
Addressed in the initial commit comment and in the discussion of the PR. Look three or four comments back.
________________________________

**Pull request merged**
