### PR TITLE
Added Manifest sos-supportconfig

### PR DESCRIPTION
**Pull request by toddhammer**
This added a manifest to pull sosreports and supportconfig when a support engineer chooses this in inspect disk.

### CODE REVIEW

**Comment by chintanrp** [comment]
@toddhammer  - Any specific reason we are adding new manifest instead of updating any existing manifest?

**Comment by toddhammer** [comment]
Hi, I added a new request because sosreport and supportconfig grabs MANY settings and also includes logs. These two commands packages all of this up into a single file. 
If we add this to the existing manifest, we will be doubling up on downloading the logs. Sometimes logs are significantly large.

**Comment by chintanrp** [comment]
@toddhammer  - That make sense, but introducing new manifest involve changes to 3 other different services to make it available on Azure Support Center. And that's the concern.

**Comment by toddhammer** [comment]
I understand. I'll abandon this one and add it to an existing manifest to make things simple. 
Thanks for the feedback!

**Pull request closed without merging**
